### PR TITLE
Handle end of input

### PR DESCRIPTION
**Pull request by kevinoid**
Currently prompt only listens for `'keypress'` events, which means that if the input ends (either by reaching the end of an input file or pipe, or the user sending EOF via `^D` at the terminal) prompt would never return.  This PR watches for `'end'` and `'error'` events which signal the end of input and handles it appropriately.  If any input has been received, it is returned.  If not, `null` is returned to differentiate it from the user sending empty input (i.e. just hitting Enter).

It also updates code, docs, and tests to handle returned `null` values:
- Update password and multi to recognize this value and cease reading.
- Add it to the name example so that users know to expect it.
- Add a test to check that the example behaves as expected.

Thanks for considering,
Kevin

### CODE REVIEW

**Comment by carlos8f** [comment]
Hi Kevin,

Thanks for the PR and explanation! However as it stands, it's a breaking API change and I'd rather roll out a simple bug-fix patch than do that.

A backwards-compatable alternative would be to add an optional callback, for error handling. Then the signature would be `prompt(message, [hideInput], onValue, [onError])`. I would prefer that to `val` being `null` on error. For node-cli-prompt 1.x, breaking changes would be OK, but I'd want some added features or something to make the upgrade worth it.

Note that listening to error events on things like `process.stdin` has a side effect though. Node core throws the error if there aren't any listeners, forcing a crash. The PR would silently discard such errors, which might be undesirable. Re-throwing the error inside the handler might also be ill-advised. So if this PR is re-rolled, I'd prefer to omit listening to the `error` event (have the app handle that), and just listen for the `end` event in cli-prompt.

Carlos

**Comment by kevinoid** [comment]
Ok.  Good catch about listening for `'error'` on `stdin`, the error suppression was inadvertent.  I'll definitely fix that.

Personally, I wouldn't worry about preserving a pre-1.0 API at the cost of usage complexity, but that's up to you.  What do you think should happen if the user doesn't provide an `onError` function?  Generate an `uncaughtException`?

**Comment by carlos8f** [comment]
If no onError handler provided, nothing happens (the callback won't fire but that's ok, nothing preventing the application from dealing with process.stdin events directly). There are 40+ modules depending on cli-prompt, thus I'd prefer to preserve the API :)

**Comment by kevinoid** [comment]
Those dependencies are bold if they are using `0.*` (both `^` or `~` and the semver spec treat pre-1.0 minor changes as incompatible).  But I kinda admire the level of dedication to preserving the behavior of functions which don't return in some cases.  I'll update the PR shortly.

**Comment by kevinoid** [comment]
Ok.  PR updated.  Let me know what you think of this version.

**Comment by carlos8f** [comment]
thanks! published in v0.5.0

**Comment by kevinoid** [comment]
Thanks for the quick review and merge!

**Pull request merged**
